### ISSUE TITLE
Stop using pre release version of Poetry. 

### ISSUE THREAD

**Issue by gatheluck** [cvpaperchallenge/Ascender#60]
## Why

Now [Poetry 1.2](https://github.com/python-poetry/poetry/releases/tag/1.2.0) is released as stable version. Until now, we are installing pre-released version of Poetry to use Poetry 1.2 beta due to [compatibility issue between PyTorch and Poetry](https://github.com/cvpaperchallenge/Ascender#compatibility-issue-between-pytorch-and-poetry). However, pre-released version becomes sometime unstable, so we should use stable version of Poetry 1.2 now.

## Definition of Done

- Stable version of Poetry 1.2 is installed in Dockerfile.

## How

- Stop installing pre-released version of Poetry instead intall stable version of Poetry 1.2. https://github.com/cvpaperchallenge/Ascender/blob/master/environments/Dockerfile#L32

- Build and run container and check if Poetry 1.2 surely installed in container.

**Comment by YoshikiKubotani** [comment]
I found three minor errors when tried to start the project by using poetry.

### **1. The requests package raised a RequestDependencyWarning error when using the poetry command**

When I used the poetry command like `poetry install` and `poetry init`, a RequestDependencyWarning error was raised.  The whole error message was as follows.
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
```

I think this problem was supposed to be solved [here](https://github.com/cvpaperchallenge/Ascender/blob/d35ba431d7dd2816f7a32ed43ceaa7e00afa2f83/environments/Dockerfile#L29) but I got the error above.

### **2. .venv directory generation was prohibited by the linux system**

Making a user [here](https://github.com/cvpaperchallenge/Ascender/blob/d35ba431d7dd2816f7a32ed43ceaa7e00afa2f83/environments/Dockerfile#L35) deprives users of the admin permission under the docker container, leading to the error below and making virtual environment under `.cache` outside the project root even when `in-project = true` is set in `poetry.toml`.

```
virtualenv: error: argument dest: the destination . is not write-able at /home/challenger/ascender
```

The current permission of `/home/challenger/ascender` under the docker container is as follows.

```
$ ls -l
total 80
-rw-rw-r-- 1 1003 1003  1084 Sep  2 13:50 LICENSE
-rw-rw-r-- 1 1003 1003   680 Sep  2 13:50 Makefile
-rw-rw-r-- 1 1003 1003 10180 Sep  2 13:50 README.md
drwxrwxr-x 4 1003 1003  4096 Sep  2 13:50 environments
drwxrwxr-x 2 1003 1003  4096 Sep  2 13:50 models
drwxrwxr-x 2 1003 1003  4096 Sep  2 13:50 notebooks
drwxrwxr-x 2 1003 1003  4096 Sep  2 13:50 outputs
-rw-rw-r-- 1 1003 1003 26449 Sep  2 13:50 poetry.lock
-rw-rw-r-- 1 1003 1003    31 Sep  2 13:50 poetry.toml
-rw-rw-r-- 1 1003 1003  1714 Sep  2 13:50 pyproject.toml
drwxrwxr-x 2 1003 1003  4096 Sep  2 13:50 src
drwxrwxr-x 3 1003 1003  4096 Sep  2 13:50 tests
```

### **3. Unknown `neddf` folder was made after running `docker compose up -d`**

I could not understand why, but a folder named `neddf` with no files was created under `home/challenger` (is this by design?).

**Comment by gatheluck** [comment]
Thank you! About `2. .venv directory generation was prohibited by the linux system`, please check FAQ in README.md. https://github.com/cvpaperchallenge/Ascender#permission-error-is-raised-when-execute-poetry-install

**Comment by gatheluck** [comment]
About `1. The requests package raised a RequestDependencyWarning error when using the poetry command` and `3. Unknown neddf folder was made after running docker compose up -d`, I suspect that pre-built container is used as cache. Please try `sudo docker compose up --build --force-recreate`. And double check if same error reproduce or not. @YoshikiKubotani

**Comment by gatheluck** [comment]
BTW, your way to write questions are quite nice! Easy to read to me and clearly written what issue your are facing. Good questioner!!

**Comment by YoshikiKubotani** [comment]
> Thank you! About `2. .venv directory generation was prohibited by the linux system`, please check FAQ in README.md. https://github.com/cvpaperchallenge/Ascender#permission-error-is-raised-when-execute-poetry-install

Thank you!  I just did not notice the FAQ description.

And for the 3rd issue above was not reproduced by re-running the `docker compose up -d` command.

**Comment by YoshikiKubotani** [comment]
> About `1. The requests package raised a RequestDependencyWarning error when using the poetry command` and `3. Unknown neddf folder was made after running docker compose up -d`, I suspect that pre-built container is used as cache. Please try `sudo docker compose up --build --force-recreate`. And double check if same error reproduce or not. @YoshikiKubotani

Do you think we should add this help message to the FAQ section?

**Comment by gatheluck** [comment]
Well... I guess this might be rare case... Let me update FAQ in different ticket. So in this ticket, let's focus on update Poetry to 1.2. Does this sounds OK to you?

**Comment by YoshikiKubotani** [comment]
Sure.  We can tackle that in another issue.
